/* eslint-disable no-undef */
import dotenv from "dotenv";
dotenv.config();

import cors from "cors";
import express from "express";
import morgan from "morgan";
import nodemailer from "nodemailer";
import axios from "axios";
import rateLimit from "express-rate-limit";
import multer from "multer";


const app = express();

// ─── Middleware ──────────────────────────────────────────────────────────────
app.use(cors());
app.use(morgan("dev"));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// ─── Rate Limiting (max 5 email requests per 15 min per IP) ─────────────────
const emailRateLimiter = rateLimit({
  windowMs: 15 * 60 * 1000,
  max: 5,
  standardHeaders: true,
  legacyHeaders: false,
  message: {
    message: "Too many requests from this IP, please try again after 15 minutes.",
  },
});

// ─── Reusable Nodemailer Transporter ────────────────────────────────────────
const transporter = nodemailer.createTransport({
  service: "gmail",
  secure: true,
  auth: {
    user: process.env.USER_AUTH_EMAIL,
    pass: process.env.USER_AUTH_PASSWORD,
  },
});

transporter.verify((error) => {
  if (error) {
    console.error("❌ Mail transporter error:", error.message);
  } else {
    console.log("✅ Mail transporter is ready");
  }
});

// ─── Helpers ─────────────────────────────────────────────────────────────────
/**
 * Verifies a Google reCAPTCHA token.
 * @returns {boolean} true if valid
 */
async function verifyCaptcha(token) {
  const url = `https://www.google.com/recaptcha/api/siteverify?secret=${process.env.CAPTCHA_SECRET_KEY}&response=${token}`;
  const { data } = await axios.post(url);
  return data.success === true;
}

/**
 * Strips HTML tags from user-supplied strings to prevent injection.
 */
function sanitize(str = "") {
  return String(str).replace(/<[^>]*>/g, "").trim();
}

// ─── HTML Email Template Helpers ─────────────────────────────────────────────
function wrapEmailHtml(title, bodyHtml) {
  return `
  <!DOCTYPE html>
  <html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>${title}</title>
    <style>
      body { margin: 0; padding: 0; background: #0d0d0d; font-family: 'Segoe UI', Arial, sans-serif; color: #e0e0e0; }
      .wrapper { max-width: 620px; margin: 40px auto; background: #1a1a2e; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 30px rgba(0,0,0,0.5); }
      .header { background: linear-gradient(135deg, #7c3aed, #a855f7); padding: 32px 40px; }
      .header h1 { margin: 0; font-size: 22px; color: #fff; letter-spacing: 0.5px; }
      .header p { margin: 6px 0 0; font-size: 13px; color: rgba(255,255,255,0.75); }
      .body { padding: 32px 40px; }
      .field { margin-bottom: 20px; }
      .field label { display: block; font-size: 11px; text-transform: uppercase; letter-spacing: 1px; color: #a855f7; margin-bottom: 4px; }
      .field p { margin: 0; font-size: 15px; color: #e0e0e0; background: #0f0f23; border-radius: 8px; padding: 10px 14px; word-break: break-word; }
      .message-box { white-space: pre-wrap; }
      .divider { height: 1px; background: #2e2e4a; margin: 24px 0; }
      .footer { background: #111128; padding: 18px 40px; text-align: center; font-size: 12px; color: #555; }
      .badge { display: inline-block; padding: 3px 10px; border-radius: 20px; font-size: 11px; font-weight: 600; background: #7c3aed22; color: #a855f7; border: 1px solid #7c3aed55; margin-bottom: 12px; }
    </style>
  </head>
  <body>
    <div class="wrapper">
      <div class="header">
        <h1>${title}</h1>
        <p>Received via TENI Website · ${new Date().toLocaleString("en-IN", { timeZone: "Asia/Kolkata" })}</p>
      </div>
      <div class="body">
        ${bodyHtml}
      </div>
      <div class="footer">
        This email was auto-generated by the TENI website contact system. Do not reply directly.
      </div>
    </div>
  </body>
  </html>
  `;
}

function contactEmailHtml({ name, email, phone, subject, message }) {
  return wrapEmailHtml("📬 New Contact Message", `
    <div class="badge">Contact Form</div>
    <div class="field"><label>Name</label><p>${name}</p></div>
    <div class="field"><label>Email</label><p><a href="mailto:${email}" style="color:#a855f7;">${email}</a></p></div>
    ${phone ? `<div class="field"><label>Phone</label><p>${phone}</p></div>` : ""}
    <div class="field"><label>Subject</label><p>${subject}</p></div>
    <div class="divider"></div>
    <div class="field"><label>Message</label><p class="message-box">${message}</p></div>
  `);
}

function cvEmailHtml({ name, email, phone, position, note }) {
  return wrapEmailHtml("📄 New CV / Job Application", `
    <div class="badge">CV Application</div>
    <div class="field"><label>Applicant Name</label><p>${name}</p></div>
    <div class="field"><label>Email</label><p><a href="mailto:${email}" style="color:#a855f7;">${email}</a></p></div>
    ${phone ? `<div class="field"><label>Phone</label><p>${phone}</p></div>` : ""}
    <div class="field"><label>Applying For</label><p>${position}</p></div>
    ${note ? `<div class="divider"></div><div class="field"><label>Note</label><p class="message-box">${note}</p></div>` : ""}
  `);
}

// ─── Route 1: Contact Form (/api/sendmail) ───────────────────────────────────
app.post("/api/sendmail", emailRateLimiter, async (req, res) => {
  const { name, email, phone, subject, message, captchaKey } = req.body;

  // Validation
  if (!name || !email || !subject || !message) {
    return res.status(400).json({ message: "Please fill in all required fields." });
  }

  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
    return res.status(400).json({ message: "Invalid email address." });
  }

  if (process.env.CAPTCHA_SECRET_KEY && captchaKey) {
    try {
      const captchaOk = await verifyCaptcha(captchaKey);
      if (!captchaOk) {
        return res.status(400).json({ message: "CAPTCHA verification failed. Please try again." });
      }
    } catch {
      return res.status(500).json({ message: "Could not verify CAPTCHA. Please try again later." });
    }
  }

  // Sanitize inputs
  const safe = {
    name: sanitize(name),
    email: sanitize(email),
    phone: sanitize(phone || ""),
    subject: sanitize(subject),
    message: sanitize(message),
  };

  const mailOptions = {
    from: `"TENI Website" <${process.env.USER_AUTH_EMAIL}>`,
    to: process.env.USER_RECEIVER_AUTH_EMAIL,
    replyTo: safe.email,
    subject: `[Contact] ${safe.subject} — from ${safe.name}`,
    text: `Name: ${safe.name}\nEmail: ${safe.email}\nPhone: ${safe.phone || "N/A"}\nSubject: ${safe.subject}\n\nMessage:\n${safe.message}`,
    html: contactEmailHtml(safe),
  };

  try {
    await transporter.sendMail(mailOptions);
    console.log(`✅ Contact email sent from ${safe.email}`);
    return res.status(200).json({ message: "Message sent successfully!" });
  } catch (error) {
    console.error("❌ Contact email error:", error.message);
    return res.status(500).json({ message: "Failed to send message. Please try again later." });
  }
});

// ─── Multer (in-memory storage for CV file attachments) ────────────────────
const upload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: 5 * 1024 * 1024 }, // 5 MB
  fileFilter: (_req, file, cb) => {
    const allowed = [".pdf", ".doc", ".docx"];
    const ext = file.originalname.toLowerCase().slice(file.originalname.lastIndexOf("."));
    if (allowed.includes(ext)) {
      cb(null, true);
    } else {
      cb(new Error("Only PDF, DOC, and DOCX files are allowed."));
    }
  },
});

// ─── Route 2: CV / Job Application Form (/api/sendcv) ───────────────────────
app.post("/api/sendcv", emailRateLimiter, upload.single("cv"), async (req, res) => {
  // Expect multipart/form-data with optional file attachment handled by frontend
  const { name, email, phone, position, note, captchaKey } = req.body;

  // Validation
  if (!name || !email || !position) {
    return res.status(400).json({ message: "Name, email, and position are required." });
  }

  if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
    return res.status(400).json({ message: "Invalid email address." });
  }

  if (process.env.CAPTCHA_SECRET_KEY && captchaKey) {
    try {
      const captchaOk = await verifyCaptcha(captchaKey);
      if (!captchaOk) {
        return res.status(400).json({ message: "CAPTCHA verification failed. Please try again." });
      }
    } catch {
      return res.status(500).json({ message: "Could not verify CAPTCHA. Please try again later." });
    }
  }

  // Sanitize inputs
  const safe = {
    name: sanitize(name),
    email: sanitize(email),
    phone: sanitize(phone || ""),
    position: sanitize(position),
    note: sanitize(note || ""),
  };

  const mailOptions = {
    from: `"TENI Website" <${process.env.USER_AUTH_EMAIL}>`,
    to: process.env.USER_RECEIVER_AUTH_EMAIL,
    replyTo: safe.email,
    subject: `[CV Application] ${safe.name} — ${safe.position}`,
    text: `Applicant: ${safe.name}\nEmail: ${safe.email}\nPhone: ${safe.phone || "N/A"}\nPosition: ${safe.position}\n\nNote:\n${safe.note || "N/A"}`,
    html: cvEmailHtml(safe),
    attachments: req.file
      ? [{
        filename: req.file.originalname,
        content: req.file.buffer,
        contentType: req.file.mimetype,
      }]
      : [],
  };

  try {
    await transporter.sendMail(mailOptions);
    console.log(`✅ CV application email received from ${safe.email} for "${safe.position}"${req.file ? ` (with attachment: ${req.file.originalname})` : ""}`);
    return res.status(200).json({ message: "Application submitted successfully!" });
  } catch (error) {
    console.error("❌ CV email error:", error.message);
    return res.status(500).json({ message: "Failed to submit application. Please try again later." });
  }
});

// ─── Health Check ────────────────────────────────────────────────────────────
app.get("/health", (_req, res) => {
  res.status(200).json({ status: "ok", time: new Date().toISOString() });
});

// ─── 404 Fallback ────────────────────────────────────────────────────────────
app.use((_req, res) => {
  res.status(404).json({ message: "Route not found." });
});

app.get("/success", (req, res) => {
  return res.status(200).json({
    message: "Deploy successfull"
  })
})

// ─── Start Server ────────────────────────────────────────────────────────────
app.listen(process.env.PORT, () => {
  console.log(`🚀 Server running on port ${process.env.PORT}`);
});

export default app;
